version: '3.7'

services:
  krateo.be:
    build: .
    container_name: krateo.be
    image: krateo/krateo-dashboard-backend
    restart: always
    environment:
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_USER=maurosala
      - POSTGRES_PASSWORD=
      - K8S_MINIKUBE_TOKEN=token
    ports:
      - 7007:7007
